import type { Metadata } from 'next';
import 'scss/HardReset.css';
import 'scss/admin/NavPanel.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'scss/admin/ProductList.scss';
import { AdminLayoutProps } from '@/helpers/interface/interfaces';
import { NavPanel } from "./NavPanel";

export const metadata: Metadata = {
  title: 'Balloons',
  description: 'Generated by Balloons',
}

const AdminLayout = ({ children }: AdminLayoutProps) => {
  return (
    <main>
      <div className="admin_nav_panel">
        <NavPanel />
      </div>
      {children}
    </main>
  );
};

export default AdminLayout;
