import type { Metadata } from 'next';
import 'scss/HardReset.css';
import 'scss/admin/NavPanel.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'scss/admin/ProductList.scss';
import { NavPanel } from "./NavPanel";

export const metadata: Metadata = {
  title: 'Balloons',
  description: 'Generated by Balloons',
}
export default function adminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <section>
    <div className="admin_nav_panel">
      <NavPanel />
    </div>{children}
  </section>
}
