import { NavPanel } from "@/app/admin/NavPanel";
import type { Metadata } from 'next';
import 'scss/HardReset.css';
import 'scss/admin/NavPanel.scss';

export const metadata: Metadata = {
  title: 'Balloonssdfdsfdfafsf',
  description: 'Generated by Balloons',
}

const Home: React.FC = () => {
  return (
    <main className="admin_nav_panel">
      <NavPanel />
    </main>
  );
}

export default Home;
