import type { Metadata } from 'next';
import './globals.css';
import 'scss/HardReset.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'Ballons',
  description: 'Generated by Balons',
}

export default function RootLayout({ params, 
  children,
}: {
  children: React.ReactNode
  }) {
  console.log( params )
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
