import type { Metadata } from 'next'
import './globals.css'
import 'scss/HardReset.css'

export const metadata: Metadata = {
  title: 'Ballons',
  description: 'Generated by Balons',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
