import type { Metadata } from 'next';
import 'scss/HardReset.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'scss/user/NavPanel.scss'
import { HeaderNavigation } from '@/components/HeaderNavigation';
import 'scss/user/ShowProductUser.scss'

export const metadata: Metadata = {
  title: 'Balloons',
  description: 'Generated by Balloons',
}
export default function UserProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <section>
    <HeaderNavigation />
    {children}
  </section>
}
